apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  namespace: {{ .Values.namespace }}
  labels:
    app: realtime-app
spec:
  selector:
    app: realtime-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
